version: '3'

services:
  captain-sim:
    build: .
    ports:
      - '8887:8080'
    environment:
      NODE_ENV: development
      DAV_API_URL: http://mission-control:8443
      CAPTAIN_PORT: 8080
      CAPTAIN_HOSTNAME: 0.0.0.0
    volumes:
      - .:/app
    networks:
      - dav
    external_links:
      - missioncontrol_missioncontrol_1:mission-control
networks:
  dav:
    external: true
