version: '3'

services:
  caption-sim:
    build: .
    ports:
      - '8887:8080'
    environment:
      NODE_ENV: development
      DAV_API_URL: https://api.dav.network:8888
      CAPTAIN_PORT: 8080
      CAPTAIN_HOSTNAME: 0.0.0.0
    volumes:
      - .:/app
    networks:
      - dav
networks:
  dav:
    external: true
