branch-defaults:
  master:
    environment: captain-sim-stg
global:
  application_name: captain-sim
  branch: null
  default_ec2_keyname: captain-sim-key
  default_platform: Docker 17.09.1-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli-dav
  repository: null
  sc: git
  workspace_type: Application
